# Generated by Django 3.0.6 on 2020-05-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='timer',
            field=models.FloatField(null=True),
        ),
    ]
