# Generated by Django 3.1.2 on 2021-01-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20201108_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='timeout',
        ),
    ]
