# Generated by Django 3.1.2 on 2021-01-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20210106_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='timer',
            field=models.IntegerField(default=1),
        ),
    ]
