# Generated by Django 3.1.2 on 2020-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20200528_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='timer',
            field=models.IntegerField(null=True),
        ),
    ]
